# Generated by Django 3.0.7 on 2022-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0038_auto_20220121_1100'),
    ]

    
